DROP TABLE IF EXISTS sucursales CASCADE;
DROP TABLE IF EXISTS comunas CASCADE;
DROP TABLE IF EXISTS regiones CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;

CREATE TABLE regiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre_region VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_regiones_nombre_region UNIQUE (nombre_region)
);

CREATE TABLE comunas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre_comuna VARCHAR(30) NOT NULL,
    nombre_region VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_comunas_nombre_comuna UNIQUE (nombre_comuna),
    CONSTRAINT fk_comunas_nombre_region FOREIGN KEY (nombre_region) REFERENCES regiones (nombre_region)
);

CREATE TABLE sucursales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre_sucursal VARCHAR(30) NOT NULL,
    nombre_comuna VARCHAR(30) NOT NULL,
    direccion_fisica VARCHAR(100) NOT NULL,
    telefono_contacto VARCHAR(255),
    estado VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_sucursales_nombre_sucursal UNIQUE (nombre_sucursal),
    CONSTRAINT uk_sucursales_direccion_fisica UNIQUE (direccion_fisica),
    CONSTRAINT uk_sucursales_telefono_contacto UNIQUE (telefono_contacto),
    CONSTRAINT fk_sucursales_nombre_comuna FOREIGN KEY (nombre_comuna) REFERENCES comunas (nombre_comuna)
);
